[versions]
composePayButton = "1.2.0"
detektRulesLibraries = "1.23.8"
detektRulesRuleauthors = "1.23.8"
sdk = "0.4.0"
sdkApiVersion = "2025-10-16.lithium"
activityCompose = "1.12.4"
agp = "8.13.2"
appcompat = "1.7.1"
arrow = "2.2.1.1"
chucker = "4.3.0"
coilNetworkOkhttp = "3.3.0"
coilCompose = "3.3.0"
composeBom = "2026.02.00"
coreKtx = "1.17.0"
datastore = "1.2.0"
detekt = "1.23.7"
espressoCore = "3.7.0"
google-services = "4.4.4"
jetbrainsKotlinJvm = "2.3.10"
junit = "4.13.2"
koinAndroidxCompose = "4.1.1"
koinAndroidxComposeNavigation = "4.1.1"
kotlin = "2.3.10"
kotlinx-serialization-json = "1.10.0"
kotlinxCoroutinesTest = "1.10.2"
kotlinxDatetime = "0.7.1-0.6.x-compat"
ksp = "2.3.5"
kover = "0.9.4"
lifecycleRuntimeKtx = "2.10.0"
material = "1.13.0"
mockk = "1.14.9"
moshi = "1.15.2"
navigationCompose = "2.9.7"
okhttp3 = "5.3.2"
protobufJavalite = "4.33.5"
retrofit2 = "3.0.0"
stripe = "22.8.0"
test-extensions = "1.3.0"
turbine = "1.2.1"
version-catalog-linter = "1.1.0"
protobuf = "0.9.6"
preference = "1.2.1"
fragmentCompose = "1.8.9"
materialIconsExtended = "1.7.8"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "test-extensions" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "materialIconsExtended" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
arrow-core = { module = "io.arrow-kt:arrow-core" }
arrow-stack = { module = "io.arrow-kt:arrow-stack", version.ref = "arrow" }
arrow-fx-coroutines = { module = "io.arrow-kt:arrow-fx-coroutines" }
chucker-no-op = { module = "com.github.chuckerteam.chucker:library-no-op", version.ref = "chucker" }
chucker = { module = "com.github.chuckerteam.chucker:library", version.ref = "chucker" }
coil3-coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }
coil3-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coilNetworkOkhttp" }
compose-pay-button = { module = "com.google.pay.button:compose-pay-button", version.ref = "composePayButton" }
converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit2" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
detekt-rules-libraries = { module = "io.gitlab.arturbosch.detekt:detekt-rules-libraries", version.ref = "detektRulesLibraries" }
detekt-rules-ruleauthors = { module = "io.gitlab.arturbosch.detekt:detekt-rules-ruleauthors", version.ref = "detektRulesRuleauthors" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koinAndroidxCompose" }
koin-androidx-compose-navigation = { module = "io.insert-koin:koin-androidx-compose-navigation", version.ref = "koinAndroidxComposeNavigation" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
moshi-adapters = { group = "com.squareup.moshi", name = "moshi-adapters", version.ref = "moshi" }
moshi-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi" }
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp3" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp3" }
protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobufJavalite" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit2" }
retrofit-scalars = { group = "com.squareup.retrofit2", name = "converter-scalars", version.ref = "retrofit2" }
stripe-android = { module = "com.stripe:stripe-android", version.ref = "stripe" }
androidx-preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
androidx-fragment-compose = { group = "androidx.fragment", name = "fragment-compose", version.ref = "fragmentCompose" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

[bundles]
networking = [
    "converter-moshi",
    "moshi",
    "moshi-adapters",
    "moshi-codegen",
    "moshi-kotlin",
    "okhttp",
    "okhttp-logging",
    "retrofit",
    "retrofit-scalars"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
serializable = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
version-catalog-linter = { id = "io.github.pemistahl.version-catalog-linter", version.ref = "version-catalog-linter" }
maven-publish = { id = "maven-publish" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf" }
